# ===================================
#  List Behavior Config
# ===================================

title: Subscribers
list: ~/plugins/przemyslawdev/news/models/subscriber/list_columns.yaml
modelClass: PrzemyslawDev\News\Models\Subscriber

recordsPerPage: 15